openapi: 3.0.3
info:
  title: Splitup
  description: App to share expenses among friends
  contact:
    name: Splitup Dev Team
    url: https://github.com/manojnakp/splitup/issues
    email: manojna.gopher@gmail.com
  license:
    name: MIT license
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: /
    description: url at which the api server is hosted
security: []
paths:
  /health:
    $ref: paths/health.yaml
  /:
    $ref: paths.yaml
  /{id}:
    $ref: paths/{id}.yaml
  /{id}/participants:
    $ref: paths/{id}_participants.yaml
  /{id}/participants/{name}:
    $ref: paths/{id}_participants_{name}.yaml
  /{id}/expenses:
    $ref: paths/{id}_expenses.yaml
  /{id}/expenses/{eid}:
    $ref: paths/{id}_expenses_{eid}.yaml
  /{id}/balance:
    $ref: paths/{id}_balance.yaml
tags:
  - name: splitcount
    description: CRUD Splitcounts
  - name: participant
    description: Participants can be modified only if not involved in any expense
  - name: expense
    description: Expenses of a Splitcount
  - name: other
    description: Balancing expenses among friends and other handy tools
